# Generated by Django 5.0.4 on 2024-04-17 19:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailsSent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_column="uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(db_column="subject", max_length=100),
                ),
                (
                    "message",
                    models.TextField(db_column="message", max_length=600),
                ),
                (
                    "addressee",
                    models.EmailField(
                        db_column="addressee", db_index=True, max_length=90
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(db_column="additional_info"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date_joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Sent",
                "verbose_name_plural": "Emails Sent",
                "db_table": "emails_sent",
                "ordering": ["-date_joined"],
            },
        ),
    ]
