# Generated by Django 5.0.4 on 2024-04-16 04:07

import apps.users.models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseUser",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_column="uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_column="email",
                        db_index=True,
                        max_length=90,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(db_column="password", max_length=128),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="is active", db_index=True, default=False
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(db_column="is_staff", default=False),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        db_column="is_superuser", default=False
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, db_column="last login", null=True
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base user",
                "verbose_name_plural": "Base users",
                "db_table": "base_user",
                "ordering": ["is_active", "-date_joined"],
            },
            managers=[
                ("objects", apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="JWT",
            fields=[
                (
                    "jwt_uuid",
                    models.UUIDField(
                        db_column="jwt_uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_uuid",
                    models.UUIDField(db_column="user_uuid", db_index=True),
                ),
                (
                    "jti",
                    models.CharField(
                        db_column="jti",
                        db_index=True,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("token", models.TextField(db_column="token")),
                ("expires_at", models.DateTimeField(db_column="expires_at")),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date joined"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "JWT",
                "verbose_name_plural": "JWT's",
                "db_table": "jwt",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="PetSex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("sex", models.CharField(db_column="sex", max_length=50)),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet sex",
                "verbose_name_plural": "Pet sexs",
                "db_table": "pet_sex",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="PetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(db_column="type", max_length=50)),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet type",
                "verbose_name_plural": "Pet types",
                "db_table": "pet_type",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "base_user",
                    models.OneToOneField(
                        db_column="base_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admin_name",
                    models.CharField(
                        db_column="admin_name", max_length=50, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admins",
                "db_table": "admin",
                "ordering": ["-base_user__date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "base_user",
                    models.OneToOneField(
                        db_column="base_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shelter_name",
                    models.CharField(
                        db_column="shelter_name", max_length=50, unique=True
                    ),
                ),
                (
                    "shelter_address",
                    models.CharField(
                        db_column="shelter_address", max_length=100
                    ),
                ),
                (
                    "shelter_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_column="shelter_phone_number",
                        max_length=25,
                        region=None,
                    ),
                ),
                (
                    "shelter_responsible",
                    models.CharField(
                        db_column="shelter_responsible", max_length=50
                    ),
                ),
                ("shelter_logo", models.URLField(db_column="shelter_logo")),
            ],
            options={
                "verbose_name": "Shelter",
                "verbose_name_plural": "Shelters",
                "db_table": "shelter",
                "ordering": ["-base_user__date_joined"],
            },
        ),
        migrations.CreateModel(
            name="JWTBlacklist",
            fields=[
                (
                    "token_id",
                    models.OneToOneField(
                        db_column="token_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.jwt",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date_joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "JWT blacklist",
                "verbose_name_plural": "JWT blacklist",
                "db_table": "jwt_blacklist",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="UserDirectory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_column="uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_uuid",
                    models.UUIDField(
                        db_column="user_uuid", db_index=True, unique=True
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "User directory",
                "verbose_name_plural": "User directories",
                "db_table": "user_directory",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "pet_uuid",
                    models.UUIDField(
                        db_column="pet_uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pet_name",
                    models.CharField(db_column="pet_name", max_length=50),
                ),
                (
                    "pet_race",
                    models.CharField(db_column="pet_race", max_length=50),
                ),
                ("pet_age", models.IntegerField(db_column="pet_age")),
                (
                    "pet_observations",
                    models.CharField(
                        db_column="pet_observations",
                        default="sin observaciones",
                        max_length=200,
                    ),
                ),
                (
                    "pet_description",
                    models.CharField(
                        db_column="pet_description",
                        default="sin descripciones",
                        max_length=200,
                    ),
                ),
                (
                    "pet_image",
                    models.URLField(
                        db_column="pet_image",
                        default="https://imagedefault.com",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date joined"
                    ),
                ),
                (
                    "pet_sex",
                    models.ForeignKey(
                        db_column="pet_sex",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.petsex",
                    ),
                ),
                (
                    "pet_type",
                    models.ForeignKey(
                        db_column="pet_type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.pettype",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        db_column="shelter",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.shelter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "db_table": "pet",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.AddIndex(
            model_name="baseuser",
            index=models.Index(
                fields=["email", "is_active"], name="email_is_active_idx"
            ),
        ),
    ]
