# Generated by Django 5.0.4 on 2024-04-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="shelter_name",
            field=models.CharField(db_column="shelter_name", max_length=50),
        ),
    ]
