# Generated by Django 4.2.11 on 2024-04-03 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="uuid",
            field=models.UUIDField(
                db_column="uuid",
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_column="uuid",
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
