# Generated by Django 5.0.4 on 2024-04-13 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_shelter_shelter_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetSex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("sex", models.CharField(db_column="sex", max_length=50)),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "pet_sex",
                "verbose_name_plural": "pet_sexs",
                "db_table": "pet_sexs",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="PetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(db_column="type", max_length=50)),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "pet_type",
                "verbose_name_plural": "pet_types",
                "db_table": "pet_types",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.RemoveField(
            model_name="pet",
            name="type_pet",
        ),
        migrations.RemoveField(
            model_name="jwtblacklist",
            name="token_id",
        ),
        migrations.AddField(
            model_name="jwtblacklist",
            name="token",
            field=models.OneToOneField(
                db_column="token",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.jwt",
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="admin_name",
            field=models.CharField(
                db_column="admin_name", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="base_user",
            field=models.OneToOneField(
                db_column="base_user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="shelter",
            field=models.ForeignKey(
                db_column="shelter",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.shelter",
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="base_user",
            field=models.OneToOneField(
                db_column="base_user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="shelter_name",
            field=models.CharField(
                db_column="shelter_name", max_length=50, unique=True
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="pet_sex",
            field=models.ForeignKey(
                db_column="pet_sex",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.petsex",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="pet_type",
            field=models.ForeignKey(
                db_column="pet_type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.pettype",
            ),
        ),
        migrations.DeleteModel(
            name="TypePet",
        ),
    ]
