# Generated by Django 5.0.3 on 2024-04-04 03:31

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_shelter_uuid_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_column="phone_number", max_length=25, region=None
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_column="email", db_index=True, max_length=90, unique=True
            ),
        ),
    ]
