# Generated by Django 5.0.4 on 2024-04-07 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_shelter_phone_number_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="JWT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "jti",
                    models.CharField(
                        db_column="jti",
                        db_index=True,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("token", models.TextField(db_column="token")),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date_joined"
                    ),
                ),
                ("expires_at", models.DateTimeField(db_column="expires_at")),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "jwt",
                "verbose_name_plural": "jwts",
                "db_table": "jwt",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="JWTBlacklisted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date_joined"
                    ),
                ),
                (
                    "token",
                    models.OneToOneField(
                        db_column="token_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.jwt",
                    ),
                ),
            ],
            options={
                "verbose_name": "jwt_blacklisted",
                "verbose_name_plural": "jwts_blacklisted",
                "db_table": "jwt_blacklisted",
                "ordering": ["-date_joined"],
            },
        ),
    ]
