# Generated by Django 5.0.4 on 2024-04-09 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_jwt_jwtblacklisted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_column="uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admins",
                "db_table": "admins",
                "ordering": ["-user__date_joined"],
            },
        ),
    ]
