# Generated by Django 4.2.11 on 2024-04-10 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypePet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=50)),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "TypePet",
                "verbose_name_plural": "TypePets",
                "db_table": "type_pet",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_column="uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=50)),
                ("race", models.CharField(db_column="race", max_length=50)),
                ("age", models.IntegerField(db_column="age")),
                (
                    "observations",
                    models.CharField(
                        db_column="observations",
                        default="sin observaciones",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_column="description",
                        default="sin descripciones",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        db_column="image",
                        default="https://imagedefault.com",
                        unique=True,
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date joined"
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        db_column="shelter",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.shelter",
                    ),
                ),
                (
                    "type_pet",
                    models.ForeignKey(
                        db_column="type_pet",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.typepet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "db_table": "pets",
                "ordering": ["-date_joined"],
            },
        ),
    ]
